extends Node

signal battle_started
signal battle_ended
signal unit_spawned(unit: UnitInstance)
signal unit_moved(unit: UnitInstance)
signal unit_died(unit: UnitInstance)
signal frontline_changed(group: BattleGroup)
signal target_changed(unit: UnitInstance, new_target: UnitInstance)
signal attack_started(attacker: UnitInstance, target: UnitInstance)
signal attack_finished(action: GameAction)
signal action_performed(action: GameAction)
signal resource_changed(resource_id: String, current_value: int, maximum: int)
signal resource_spent(resource_id: String, amount: int, remaining: int)
signal resource_generated(resource_id: String, amount: int, current_value: int)
signal projectile_spawned(projectile: ProjectileInstance)
signal projectile_moved(projectile: ProjectileInstance)
signal projectile_collided(projectile: ProjectileInstance, target: UnitInstance)
signal projectile_destroyed(projectile: ProjectileInstance)
signal affinity_debug(attacker_affinity: String, defender_affinity: String, attack_modifiers: CombatModifierCollection, final_damage: int)
signal effect_applied(effect: EffectInstance)
signal effect_removed(effect: EffectInstance)
signal effect_expired(effect: EffectInstance)
signal effect_refreshed(effect: EffectInstance)
signal effect_stack_changed(effect: EffectInstance)
