extends Node

signal battle_started
signal battle_ended
signal unit_spawned(unit: UnitInstance)
signal unit_moved(unit: UnitInstance)
signal unit_died(unit: UnitInstance)
signal frontline_changed(group: BattleGroup)
signal target_changed(unit: UnitInstance, new_target: UnitInstance)
signal attack_started(attacker: UnitInstance, target: UnitInstance)
signal attack_finished(action: GameAction)
signal action_performed(action: GameAction)
signal resource_changed(resource_id: String, current_value: int, maximum: int)
signal resource_spent(resource_id: String, amount: int, remaining: int)
signal resource_generated(resource_id: String, amount: int, current_value: int)
signal projectile_spawned(projectile: ProjectileInstance)
signal projectile_moved(projectile: ProjectileInstance)
signal projectile_collided(projectile: ProjectileInstance, target: UnitInstance)
signal projectile_destroyed(projectile: ProjectileInstance)
signal affinity_debug(attacker_affinity: String, defender_affinity: String, attack_modifiers: CombatModifierCollection, final_damage: int)
signal effect_applied(effect: EffectInstance)
signal effect_removed(effect: EffectInstance)
signal effect_expired(effect: EffectInstance)
signal effect_refreshed(effect: EffectInstance)
signal effect_stack_changed(effect: EffectInstance)
signal ability_started(ability: AbilityInstance)
signal ability_finished(ability: AbilityInstance)
signal ability_cancelled(ability_id: String, owner: UnitInstance)
signal ability_cooldown_started(ability_id: String, owner: UnitInstance, duration: float)
signal ability_ready(ability_id: String, owner: UnitInstance)
signal match_started
signal match_paused
signal match_resumed
signal match_finished(winner: String, loser: String, elapsed_time: float)
signal victory(winner: String, condition: String)
signal defeat(loser: String, condition: String)
signal draw(condition: String)
signal countdown_started(duration: float)
signal nexus_damaged(team: String, current_hp: int, max_hp: int)
signal nexus_destroyed(team: String)
signal ai_decision_started(personality_id: String)
signal ai_decision_finished(personality_id: String, action_type: String)
signal ai_command_generated(command: GameCommand, personality_id: String)
